language: go
before_install:
  - go get github.com/mattn/goveralls
jobs:
  include:
    - stage: test
      script: $GOPATH/bin/goveralls -service=travis-ci
    - stage: owners
      script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then exit 1; fi'
    
notifications:
  email: false
