language: go
before_install:
  - go get github.com/mattn/goveralls
jobs:
  include:
    - stage: test
      script: $GOPATH/bin/goveralls -service=travis-ci
    - stage: owners
      script: go run main.go check --github
notifications:
  email: false
